### ISSUE TITLE
Autobidder not working in Fifa 23 (Windows)

### ISSUE THREAD

**Issue by Swrtijf** [tmb5cg/Fifa-Autobidder#37]
Autobidder not working in Fifa 23 (Windows)

**Comment by SkyExit** [comment]
Yeah for me too
`Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\georg\Desktop\CodingStuff\Fifa-Autobidder-main\src\gui.py", line 409, in run
    autobidder_obj.run()
  File "C:\Users\georg\Desktop\CodingStuff\Fifa-Autobidder-main\src\autobidder.py", line 128, in run
    self.enterFilters()
  File "C:\Users\georg\Desktop\CodingStuff\Fifa-Autobidder-main\src\autobidder.py", line 757, in enterFilters
    webapp_filters_output = getFilters(
                            ^^^^^^^^^^^
  File "C:\Users\georg\Desktop\CodingStuff\Fifa-Autobidder-main\src\helpers.py", line 48, in getFilters
    data = json.load(json_file)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 36999: character maps to <undefined>`

**Comment by tmb5cg** [comment]
Can you provide any additional instructions? Closing but open another issue if you are having trouble
