### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by Af7eR9l0W** [tmb5cg/Fifa-Autobidder#50]
I've tried changing line 905 price.replace to add \\ but that doesn't work. Any ideas? 

> [06:39:30 PM] Autobidder started
[06:40:06 PM] Filters successfully entered
[06:40:06 PM] Fetching futbin prices (new version)...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\veloc\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "F:\FUT_TRAD\Fifa-Autobidder-main\src\gui.py", line 409, in run
    autobidder_obj.run()
  File "F:\FUT_TRAD\Fifa-Autobidder-main\src\autobidder.py", line 121, in run
    self.getFutbinList(
  File "F:\FUT_TRAD\Fifa-Autobidder-main\src\autobidder.py", line 996, in getFutbinList
    self.fetch_player_data()
  File "F:\FUT_TRAD\Fifa-Autobidder-main\src\autobidder.py", line 906, in fetch_player_data
    price = float(price)
ValueError: could not convert string to float: '2 3  \\  57 36 53 56 84 81

**Comment by therealMRBK** [comment]
same here, is  there a fix?
